#!/usr/bin/env bash
# Installs nginx web server

# Update the package list and install Nginx
apt-get update
apt-get install -y nginx

# Create the default "Hello world" page
echo "Hello World!" > /var/www/html/index.html

# Start the Nginx service
service nginx start
