#!/usr/bin/env bash

# Update the package list and install Nginx
apt-get update
apt-get install -y nginx

# Create the default "Hello world" page
echo "Hello World!" > /var/www/html/index.html

# Define the redirection configuration
redirection_config="/etc/nginx/redirect_config"

# Define the redirection configuration
echo -e "\
server {
    server_name _;
    location /redirect_me {
        return 301 https://alxafrica.com/;
    }
}" > $redirection_config

# Insert the redirection configuration into the default Nginx server block
sed -i '/server_name _;/{
    r /tmp/new_config
    d
}' /etc/nginx/sites-available/default

# Restart the Nginx service
service nginx restart
