#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page that contains the string

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Update the package list and install Nginx
apt-get update
apt-get install -y nginx

# Create the default "Hello world" page
echo "Hello World!" > /var/www/html/index.html

# Configure the custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure the server for redirection and 404 page
echo -e "\tserver_name _;
\tlocation /redirect_me {
\t\treturn 301 https://alxafrica.com/;
\t}

\terror_page 404 /404.html;
\tlocation = /404.html {
\t\troot /usr/share/nginx/html;
\t\tinternal;
\t}
" > /etc/nginx/redirect_config

sed -i '/server_name _;/{
    r /etc/nginx/redirect_config
}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx start
