#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page that contains the string

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Update the package list and install Nginx
apt-get update
apt-get install -y nginx

# Create the default "Hello world" page
echo "Hello World!" > /var/www/html/index.html

# Configure the custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure the server for redirection and 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://www.alxafrica.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx start
