#!/usr/bin/env bash
# Description: Installs and configures HAProxy for load balancing web servers.

# Define the configuration snippet to append
config_to_append="
	frontend noblet-frontend
    		bind *:80
		mode http
    		default_backend noblet_backend

	backend noblet_backend
    		balance roundrobin
    		server 530350-web-01 100.25.38.194:80 check
    		server 530350-web-02 34.224.3.62:80 check
	"

# Function to install HAProxy
function install_haproxy() {
	# Update package index
	apt-get -y update
	
	# Install necessary packages and add enable dedicated PPA for HAproxy 2.8
	apt-get install --no-install-recommends software-properties-common
	add-apt-repository ppa:vbernat/haproxy-2.8

	# Install HAProxy
	apt-get -y install haproxy
}

# Function to configure HAProxy
function configure_haproxy() {	
	# Check if the configuration snippet already exists in the file
	if ! grep -qF "$config_to_append" /etc/haproxy/haproxy.cfg; then
    		# Append the configuration snippet to the file
    		echo "$config_to_append" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null
	fi

	# Enable HAProxy by modifying the configuration file
	echo "ENABLED=1" | sudo tee -a /etc/default/haproxy >/dev/null
	
	# Restart HAProxy service
	service haproxy restart
}

# Main function
main() {
	install_haproxy
	configure_haproxy
}

# Execute main function
main
