#!/usr/bin/env bash
# This script fixes the Nginx configuration to listen on port 80.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# Restart the Nginx service to apply the changes.
service nginx restart
