#!/usr/bin/env bash
# Script for advanced task 1
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command && rm /var/run/holbertonscript.pid && exit" 15
trap "echo Y U no love me?!" 2
trap "rm /var/run/holbertonscript.pid && exit && exit" 3
while true
do
	echo To infinity and beyond
	sleep 2
done
