#!/usr/bin/env bash
# Script for advanced task 1

pid_file=/var/run/myscript.pid

echo "$$" > "$pid_file"
trap "echo I hate the kill command && rm $pid_file && exit" 15
trap "echo Y U no love me?!" 2
trap "rm $pid_file && exit && exit" 3

while true
do
	echo To infinity and beyond
	sleep 2
done
