#!/usr/bin/env bash
# This script is displaying "bad luck from China" in the 4th iteration,
# "bad luck from from Japan" in the 9th iteration,
# and "bad luck from Italy" in the 17th iteration. Otherwise it prints the num.
counter=1
while [ $counter -le 20 ]
do
	echo $counter
	case $counter in
	4) echo bad luck from China
	;;
	9) echo bad luck from Japan
	;;
	17) echo bad luck from Italy
	;;
	esac
	((counter++))
done
