#!/usr/bin/env bash
# This script gives you information about the school file.

if [ -e "school" ]; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit
fi


if [ ! -s "school" ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi


if [ -f "school" ]; then
	echo "school is a regular file"
fi
