#!/usr/bin/env bash
# This script changes the localhost and facebook.com ips.
sudo cp /etc/hosts ~/n_hosts
sed -i "s/127.0.0.1/127.0.0.2/g" ~/n_hosts
echo "8.8.8.8 facebook.com" >> ~/n_hosts
sudo cp -f ~/n_hosts /etc/hosts
