#!/usr/bin/env bash
# This script add run the whoami command under the user passed as an argument

# Check if the user provided an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run the whoami command under the provided user
sudo -u "$1" whoami
